### ISSUE TITLE
`make start` broken with issue with spandex_phoenix

### ISSUE THREAD

**Issue by dwalintukan** [poanetwork/blockscout#1200]
*Describe your issue here.*
After rebasing on the latest changes on master, the `Makefile/Dockerfile` is broken with this error.
```
...
==> spandex_phoenix
Compiling 5 files (.ex)

== Compilation error in file lib/spandex_phoenix/instrumenter.ex ==
** (RuntimeError) You must configure a :tracer for :spandex_phoenix
    lib/spandex_phoenix/instrumenter.ex:21: (module)
could not compile dependency :spandex_phoenix, "mix compile" failed. You can recompile this dependency with "mix deps.compile spandex_phoenix", update it with "mix deps.update spandex_phoenix" or clean it with "mix deps.clean spandex_phoenix"
The command '/bin/sh -c mix do deps.get, deps.compile' returned a non-zero code: 1
Makefile:55: recipe for target 'build' failed
make: *** [build] Error 1
```

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`): Docker bitwalker/alpine-elixir-phoenix:latest
* Operating System: Ubuntu 18.04.1 LTS 

### Steps to reproduce

1. Pull `master`
2. `cd docker`
3. `make start`

### Expected behaviour
Makefile completes with success and docker containers start.

### Actual behaviour
Makefile errors with `spandex_phoenix` error.

**Comment by acravenho** [comment]
@zachdaniel Can you please assist here?

**Comment by natlg** [comment]
Seems it's because `spandex_phoenix` dependency needs `BlockScoutWeb.Tracer` module for compiling. But `Dockerfile` describes to compile dependencies first and copy all other files after that, so they are not available during compilation.
Worked when I added `ADD . .` [here](https://github.com/poanetwork/blockscout/blob/44e4f17d142b26314513ab646e1f73c06a547dae/docker/Dockerfile#L10)  and removed all other `ADD` commands.

**Comment by zachdaniel** [comment]
Interesting. Using those other `ADD` commands are an optimization to not require dep compilation when unrelated files change. Try adding `ADD apps/block_scout_web/config ./apps/block_scout_web/config`. I should see if I can't loosen this up on Spandex's side, but for now that ought to work.
